echo "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
echo "CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';"
echo "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';"
echo "FLUSH PRIVILEGES;"
