FROM mysql:8.0.31


CMD [ "mysqld" ]

# docker build --build-arg MYSQL_ROOT_PASSWORD=0000 --build-arg DB_NAME=wordpress --build-arg DB_USER=nikita --build-arg DB_PASS=0000 -t db_test requirements/mysql && docker run --rm -it -e MYSQL_ROOT_PASSWORD=0000 -it db_test bash

# docker run --rm -e MYSQL_ROOT_PASSWORD=0000 -d db_test mysqld
